[build-system]
build-backend = "hatchling.build"
requires = [ "hatchling" ]

[project]
name = "scpdac"
version = "0.1.0"
description = "Mapping single cell data into PDAC atlases"
readme = "README.md"
license = { file = "LICENSE" }
maintainers = [
  { name = "Daniele Lucarelli", email = "daniele.lucarelli@tum.de" },
]
authors = [
  { name = "Daniele Lucarelli" },
]
requires-python = ">=3.11"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
]
dependencies = [
  "scarches",
  "session-info2",
]
optional-dependencies.dev = [
  "pre-commit",
  "twine>=4.0.2",
  "scikit-learn",
  "scvi-tools",
]
optional-dependencies.doc = [
  "docutils>=0.8,!=0.18.*,!=0.19.*",
  "ipykernel",
  "ipython",
  "myst-nb>=1.1",
  "pandas",
  "setuptools",
  "sphinx>=8.1",
  "sphinx-autodoc-typehints",
  "sphinx-book-theme>=1",
  "sphinx-copybutton",
  "sphinx-tabs",
  "sphinxcontrib-bibtex>=1",
  "sphinxext-opengraph",
]
optional-dependencies.test = [
  "coverage>=7.10",
  "pytest",
  "pytest-cov",
]
optional-dependencies.eval = [
  "matplotlib",
  "seaborn",
]
urls.Documentation = "https://scPDAC.readthedocs.io/"
urls.Homepage = "https://github.com/MDLDan/scPDAC"
urls.Source = "https://github.com/MDLDan/scPDAC"

[tool.hatch.build.targets.wheel]
packages = [ "src/scpdac" ]
artifacts = [
  "*.pt",
]

[tool.hatch.envs.default]
installer = "uv"
features = [ "dev" ]

[tool.hatch.envs.docs]
features = [ "doc" ]
scripts.build = "sphinx-build -M html docs docs/_build -W {args}"
scripts.open = "python -m webbrowser -t docs/_build/html/index.html"
scripts.clean = "git clean -fdX -- {args:docs}"

[[tool.hatch.envs.hatch-test.matrix]]
deps = [ "stable" ]
python = [ "3.11", "3.14" ]

[[tool.hatch.envs.hatch-test.matrix]]
deps = [ "pre" ]
python = [ "3.14" ]

[tool.hatch.envs.hatch-test]
features = [ "dev", "test" ]

[tool.hatch.envs.hatch-test.overrides]
matrix.deps.env-vars = [
  { key = "UV_PRERELEASE", value = "allow", if = [ "pre" ] },
]

[tool.ruff]
line-length = 120
src = [ "src" ]
extend-include = [ "*.ipynb" ]
exclude = [ "tests/**" ]

format.docstring-code-format = true

lint.select = [
  "B",
  "BLE",
  "C4",
  "D",
  "E",
  "F",
  "I",
  "RUF100",
  "TID",
  "UP",
  "W",
]
lint.ignore = [
  "B008",
  "D100",
  "D104",
  "D105",
  "D107",
  "D203",
  "D213",
  "D400",
  "D401",
  "E501",
  "E731",
  "E741",
]
lint.per-file-ignores."*/__init__.py" = [ "F401" ]
lint.per-file-ignores."docs/*" = [ "I" ]
lint.per-file-ignores."tests/*" = [ "D" ]
lint.pydocstyle.convention = "numpy"

[tool.pytest.ini_options]
testpaths = [ "tests" ]
xfail_strict = true
addopts = [
  "--import-mode=importlib",
]

[tool.coverage.run]
source = [ "scpdac" ]
patch = [ "subprocess" ]
omit = [
  "**/test_*.py",
]

[tool.cruft]
skip = [
  "tests",
  "src/**/__init__.py",
  "docs/api.md",
  "docs/changelog.md",
  "docs/references.bib",
  "docs/references.md",
]
